/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef counter_CONSTANTS_H
#define counter_CONSTANTS_H

#include "counter_types.h"

namespace counterService {

class counterConstants {
 public:
  counterConstants();

};

extern const counterConstants g_counter_constants;

} // namespace

#endif
